### PR TITLE
Simple addon

### PR DESCRIPTION
**Pull request by mgejay**
To see if the owner was online, this was fairly easy to make.

### CODE REVIEW

**Comment by Fyrsta** [comment]
I don't believe this is something that's needed. Players will be able to use tab or /list to see who's on, and /list will be properly separated to make it easy for people to see who's online.

Also, you need to create (or work on) an issue before submitting a pull request in the future.

**Comment by Wild1145** [comment]
Also, not the best way to do it, going based on UUID would be more sensible in the event that @WickedGamingUK decided to change his name again

**Comment by Fyrsta** [comment]
@Wild1145 Yes, there are a good few problems with the code as well.

**Comment by mgejay** [comment]
@WickedGamingUK Wrong, tested, works.

**Comment by Fyrsta** [comment]
Just because it works doesn't mean it's without faults.

**Comment by Wild1145** [comment]
@TheRevalation Maybe you should work on your attitude before trying to work on Java projects. You do not know it all, and just saying "Wrong, tested, works" just shows that you have no understanding of the process that code needs to go through before it is accepted into any sort of project. If someone tells you what you have done is wrong, and they happen to have a decent understanding of Java, then maybe you should listen to them before just telling them that they are wrong.

**Comment by mgejay** [comment]
@Wild1145 I tested the command, Ryan. No errors, compiles, works. I may just need to add a permission node to the command. If you don't want me, closed.

**Comment by Fyrsta** [comment]
@TheRevalation 

Here are the problems with your code:
- Incorrect formatting
- Mix between Allman and K&R
- Unneeded variable declaration 
- Non descriptive variable naming
- Unneeded else-if and else statements

I'm only saying this to try and benefit you. If you take this as an insult, you're obviously too immature to take constructive criticism.

**Comment by Wild1145** [comment]
@TheRevalation Just because you test something doesnt mean its the right way of doing things, or that it will even work longer term or with other commands. @WickedGamingUK had said it did not work as it should and that it was not suitable, so instead of telling him he (project creator) is wrong, why not ask "What is wrong with it?"

**Comment by mgejay** [comment]
@WickedGamingUK @Wild1145 I forgot this command was buggy and outdated, sorry for PR'ing it.

**Pull request closed without merging**
