### PR TITLE
Command for staff

### PR DESCRIPTION
**Pull request by mgejay**
@WickedGamingUK This would be for staff, while making a plugin, you want something custom, something that makes you different, this is my old command that I reformatted for this plugin. There is a perm node, make it want you want it to be.

### CODE REVIEW

**Comment by mgejay** [comment]
You'll probably want to change if (! (sender.hasPermission to if (!tSender.hasRank(Rank.MODERATOR)) {

Is that 't' between Sender and ! supposed to be there?

**Comment by Fyrsta** [comment]
Yes, the t in tSender is needed. If you looked at the code you will know that it's a class that I've created to manage a particular player (https://github.com/TranxCraft/iTranxCraft/blob/master/src/main/java/com/wickedgaminguk/tranxcraft/player/TranxPlayer.java).

And about the PR, you need to create an issue before working on a pull request, otherwise you'll end up spending time developing something that won't be used.

I don't think this is something that's a good thing to have, for a warning like thing a simple smite is perfectly adequate.

Also, please follow the code style that exists within the project.

**Comment by mgejay** [comment]
@wickedgaminguk It is a smite.

**Comment by Fyrsta** [comment]
It strikes lightning 200 times, as well as killing the player and putting the player on fire. This is overkill for the intended need.

**Comment by mgejay** [comment]
@WickedGamingUK We can modify that .-.

**Pull request closed without merging**
